const langs = {
  fr_FR: {
    response_ban: "🚨 Nouveau ban détecté !",
    response_watch: "Profil surveillé :",
    response_type: "Type de ban",
    response_date: "Date du ban",
    bot_lang: "Le bot est maintenant en français",
    error_link: "❌ Veuillez entrer un lien Steam valide",
    error_already: "❌ Ce lien a déjà été ajouté",
  },
  en_EN: {
    response_ban: "🚨 New ban detected!",
    response_watch: "Watched profile:",
    response_type: "Ban type",
    response_date: "Ban date",
    bot_lang: "Bot is now in English",
    error_link: "❌ Please enter a valid Steam link",
    error_already: "❌ This link has already been added",
  },
  es_ES: {
    response_ban: "🚨 ¡Nueva prohibición detectada!",
    response_watch: "Perfil vigilado:",
    response_type: "Tipo de prohibición",
    response_date: "Fecha de prohibición",
    bot_lang: "El bot ahora está en español",
    error_link: "❌ Por favor, introduce un enlace de Steam válido",
    error_already: "❌ Este enlace ya ha sido añadido",
  },
  de_DE: {
    response_ban: "🚨 Neuer Bann entdeckt!",
    response_watch: "Überwachtes Profil:",
    response_type: "Bann-Typ",
    response_date: "Bann-Datum",
    bot_lang: "Bot ist jetzt auf Deutsch",
    error_link: "❌ Bitte geben Sie einen gültigen Steam-Link ein",
    error_already: "❌ Dieser Link wurde bereits hinzugefügt",
  },
  pl_PL: {
    response_ban: "🚨 Wykryto nowy ban!",
    response_watch: "Obserwowany profil:",
    response_type: "Typ bana",
    response_date: "Data bana",
    bot_lang: "Bot jest teraz w języku polskim",
    error_link: "❌ Proszę podać prawidłowy link Steam",
    error_already: "❌ Ten link został już dodany",
  },
  da_DK: {
    response_ban: "🚨 Ny ban opdaget!",
    response_watch: "Overvåget profil:",
    response_type: "Ban type",
    response_date: "Ban dato",
    bot_lang: "Bot er nu på dansk",
    error_link: "❌ Indtast venligst et gyldigt Steam-link",
    error_already: "❌ Dette link er allerede tilføjet",
  },
  tr_TR: {
    response_ban: "🚨 Yeni yasak tespit edildi!",
    response_watch: "İzlenen profil:",
    response_type: "Yasak türü",
    response_date: "Yasak tarihi",
    bot_lang: "Bot artık Türkçe",
    error_link: "❌ Lütfen geçerli bir Steam bağlantısı girin",
    error_already: "❌ Bu bağlantı zaten eklenmiş",
  },
  nl_NL: {
    response_ban: "🚨 Nieuwe ban gedetecteerd!",
    response_watch: "Bekeken profiel:",
    response_type: "Ban type",
    response_date: "Ban datum",
    bot_lang: "Bot is nu in het Nederlands",
    error_link: "❌ Voer een geldige Steam-link in",
    error_already: "❌ Deze link is al toegevoegd",
  },
  ru_RU: {
    response_ban: "🚨 Обнаружен новый бан!",
    response_watch: "Отслеживаемый профиль:",
    response_type: "Тип бана",
    response_date: "Дата бана",
    bot_lang: "Бот теперь на русском языке",
    error_link: "❌ Пожалуйста, введите действительную ссылку Steam",
    error_already: "❌ Эта ссылка уже была добавлена",
  },
  zh_CN: {
    response_ban: "🚨 检测到新的封禁！",
    response_watch: "监视的个人资料：",
    response_type: "封禁类型",
    response_date: "封禁日期",
    bot_lang: "机器人现在使用中文",
    error_link: "❌ 请输入有效的Steam链接",
    error_already: "❌ 此链接已添加",
  },
  sv_SE: {
    response_ban: "🚨 Nytt ban upptäckt!",
    response_watch: "Övervakad profil:",
    response_type: "Ban typ",
    response_date: "Ban datum",
    bot_lang: "Botten är nu på svenska",
    error_link: "❌ Ange en giltig Steam-länk",
    error_already: "❌ Denna länk har redan lagts till",
  },
  ar_SA: {
    response_ban: "🚨 تم اكتشاف حظر جديد!",
    response_watch: "الملف الشخصي المراقب:",
    response_type: "نوع الحظر",
    response_date: "تاريخ الحظر",
    bot_lang: "الروبوت الآن باللغة العربية السعودية",
    error_link: "❌ الرجاء إدخال رابط Steam صالح",
    error_already: "❌ تمت إضافة هذا الرابط بالفعل",
  },
  ar_MA: {
    response_ban: "🚨 تم اكتشاف حظر جديد!",
    response_watch: "الملف الشخصي المراقب:",
    response_type: "نوع الحظر",
    response_date: "تاريخ الحظر",
    bot_lang: "الروبوت الآن باللغة العربية المغربية",
    error_link: "❌ الرجاء إدخال رابط Steam صالح",
    error_already: "❌ تمت إضافة هذا الرابط بالفعل",
  },
  ar_AE: {
    response_ban: "🚨 تم اكتشاف حظر جديد!",
    response_watch: "الملف الشخصي المراقب:",
    response_type: "نوع الحظر",
    response_date: "تاريخ الحظر",
    bot_lang: "الروبوت الآن باللغة العربية الإماراتية",
    error_link: "❌ الرجاء إدخال رابط Steam صالح",
    error_already: "❌ تمت إضافة هذا الرابط بالفعل",
  },
  he_IL: {
    response_ban: "🚨 התגלה באן חדש!",
    response_watch: "פרופיל במעקב:",
    response_type: "סוג באן",
    response_date: "תאריך באן",
    bot_lang: "הבוט כעת בעברית",
    error_link: "❌ אנא הכנס קישור Steam תקין",
    error_already: "❌ קישור זה כבר נוסף",
  },
  ja_JP: {
    response_ban: "🚨 新しいBANが検出されました！",
    response_watch: "監視プロフィール：",
    response_type: "BANタイプ",
    response_date: "BAN日付",
    bot_lang: "ボットは日本語になりました",
    error_link: "❌ 有効なSteamリンクを入力してください",
    error_already: "❌ このリンクは既に追加されています",
  },
  ko_KR: {
    response_ban: "🚨 새로운 밴이 감지되었습니다!",
    response_watch: "감시 중인 프로필:",
    response_type: "밴 유형",
    response_date: "밴 날짜",
    bot_lang: "봇이 이제 한국어로 설정되었습니다",
    error_link: "❌ 유효한 Steam 링크를 입력해주세요",
    error_already: "❌ 이 링크는 이미 추가되었습니다",
  },
  th_TH: {
    response_ban: "🚨 ตรวจพบการแบนใหม่!",
    response_watch: "โปรไฟล์ที่ถูกติดตาม:",
    response_type: "ประเภทการแบน",
    response_date: "วันที่แบน",
    bot_lang: "บอทเป็นภาษาไทยแล้ว",
    error_link: "❌ กรุณาใส่ลิงก์ Steam ที่ถูกต้อง",
    error_already: "❌ ลิงก์นี้ถูกเพิ่มไปแล้ว",
  },
  fi_FI: {
    response_ban: "🚨 Uusi porttikielto havaittu!",
    response_watch: "Seurattu profiili:",
    response_type: "Porttikiellon tyyppi",
    response_date: "Porttikiellon päivämäärä",
    bot_lang: "Botti on nyt suomeksi",
    error_link: "❌ Syötä kelvollinen Steam-linkki",
    error_already: "❌ Tämä linkki on jo lisätty",
  },
  de_AT: {
    response_ban: "🚨 Neuer Bann entdeckt!",
    response_watch: "Überwachtes Profil:",
    response_type: "Bann-Typ",
    response_date: "Bann-Datum",
    bot_lang: "Bot ist jetzt auf Österreichischem Deutsch",
    error_link: "❌ Bitte geben Sie einen gültigen Steam-Link ein",
    error_already: "❌ Dieser Link wurde bereits hinzugefügt",
  },
  fr_BE: {
    response_ban: "🚨 Nouveau ban détecté ! une fois",
    response_watch: "Profil surveillé :",
    response_type: "Type de ban",
    response_date: "Date du ban",
    bot_lang: "Le bot est maintenant en français belge ! une fois",
    error_link: "❌ Veuillez entrer un lien Steam valide ! une fois",
    error_already: "❌ Ce lien a déjà été ajouté ! une fois",
  },
  nl_BE: {
    response_ban: "🚨 Nieuwe ban gedetecteerd!",
    response_watch: "Bekeken profiel:",
    response_type: "Ban type",
    response_date: "Ban datum",
    bot_lang: "Bot is nu in het Belgisch Nederlands",
    error_link: "❌ Voer een geldige Steam-link in",
    error_already: "❌ Deze link is al toegevoegd",
  },
  pt_PT: {
    response_ban: "🚨 Nova proibição detectada!",
    response_watch: "Perfil vigiado:",
    response_type: "Tipo de proibição",
    response_date: "Data da proibição",
    bot_lang: "Bot está agora em português",
    error_link: "❌ Por favor, insira um link Steam válido",
    error_already: "❌ Este link já foi adicionado",
  },
  pt_BR: {
    response_ban: "🚨 Novo banimento detectado!",
    response_watch: "Perfil monitorado:",
    response_type: "Tipo de banimento",
    response_date: "Data do banimento",
    bot_lang: "Bot agora está em português do Brasil",
    error_link: "❌ Por favor, insira um link Steam válido",
    error_already: "❌ Este link já foi adicionado",
  },
};

module.exports = langs;
